# Generated by Django 5.0.6 on 2024-05-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='employee')),
            ],
        ),
    ]
