# Generated by Django 5.0.6 on 2024-05-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
